[package]
name = "ngos-settings"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
capability = { path = "../../../libs/capability" }
sel4-sys = { path = "../../../libs/sel4-sys" }
tahoe-ui = { path = "../../../libs/tahoe-ui" }
cursor-assets = { path = "../../../libs/cursor-assets" }
alloc = { package = "alloc", version = "1.80" }
spin = "0.9"
hashbrown = "0.14"
anyhow = "1.0"
thiserror = "1.0"
ash = { version = "0.37", features = ["alloc"] }
serde = { version = "1.0", features = ["alloc", "derive"] }
toml = "0.8"

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1
opt-level = "z"
strip = true