[package]
name = "ngos-tahoe-ui"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
alloc = { package = "alloc", version = "1.80" }
tinyvec = "1.10"
ash = { version = "0.37", features = ["alloc"] }

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1
opt-level = "z"
strip = true