#include <X11/Xlib.h>
#include <X11/keysym.h>
#include <X11/Xatom.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>

#define BAR 46
#define DOCK_H 94
#define ICONS 5
#define MAX_CLIENTS 32
#define TITLE 30

typedef struct { Window client, frame; int x,y,w,h; int maximized, minimized; } Client;
static Display *d; static Window root, shell, focus=0; static int sw,sh,desk=0,hover=-1,dark=1;
static Client clients[MAX_CLIENTS]; static int nclients=0; static Client *drag_client=0; static int drag_mode=0, drag_x,drag_y, drag_w,drag_h;
static unsigned long col(const char *s){Colormap m=DefaultColormap(d,DefaultScreen(d));XColor c;XParseColor(d,m,s,&c);XAllocColor(d,m,&c);return c.pixel;}
static void launch(const char *cmd){if(!fork()){setsid();execl("/bin/sh","sh","-c",cmd,(char*)0);_exit(127);}}
static Client *find_client(Window w){for(int i=0;i<nclients;i++)if(clients[i].client==w||clients[i].frame==w)return &clients[i];return 0;}
static void rounded(GC g,int x,int y,int w,int h,unsigned long c){XSetForeground(d,g,c);XFillRectangle(d,shell,g,x+12,y,w-24,h);XFillRectangle(d,shell,g,x,y+12,w,h-24);XFillArc(d,shell,g,x,y,24,24,90*64,90*64);XFillArc(d,shell,g,x+w-24,y,24,24,0,90*64);XFillArc(d,shell,g,x,y+h-24,24,24,180*64,90*64);XFillArc(d,shell,g,x+w-24,y+h-24,24,24,270*64,90*64);}
static void icon(GC g,int x,int y,int i,int size){const char *cs[]={"#8bf7ff","#ff4fd8","#a77bff","#4de3a8","#ffc857"};const char *t[]={"N",">_","F","S","+"};XSetForeground(d,g,col(cs[i]));XFillArc(d,shell,g,x-size/2,y-size/2,size,size,0,360*64);XSetForeground(d,g,col(dark?"#07101d":"#f3f6ff"));XDrawString(d,shell,g,x-5,y+6,t[i],1);}
static void redraw(void){XClearWindow(d,shell);GC g=XCreateGC(d,shell,0,0);const char *base=dark?"#060914":"#e7ecf8";XSetWindowBackground(d,shell,col(base));XSetForeground(d,g,col(dark?"#11182c":"#d5ddf0"));rounded(g,0,0,sw,BAR,col(dark?"#11182c":"#d5ddf0"));XSetForeground(d,g,col(dark?"#8bf7ff":"#25304b"));XDrawString(d,shell,g,22,30,"NGOS",4);XSetForeground(d,g,col(dark?"#aeb9d8":"#465271"));char info[96];snprintf(info,sizeof info,"WORKSPACE %d/4   |   STABLE RELEASE   |   %s MODE",desk+1,dark?"DARK":"LIGHT");XDrawString(d,shell,g,sw/2-180,30,info,strlen(info));XDrawString(d,shell,g,sw-160,30,"SETTINGS  [D]",13);rounded(g,sw/2-220,sh-DOCK_H,440,70,col(dark?"#18223b":"#d5ddf0"));XSetForeground(d,g,col(dark?"#314264":"#aeb9d8"));XDrawRectangle(d,shell,g,sw/2-220,sh-DOCK_H,439,69);int center=sw/2;for(int i=0;i<ICONS;i++){int dx=(i-2)*72;int dist=abs(i-(hover<0?2:hover));int sz=dist==0?58:(dist==1?49:42);int yy=sh-DOCK_H+35-(dist==0?10:0);icon(g,center+dx,yy,i,sz);}XSetForeground(d,g,col(dark?"#7584a8":"#465271"));XDrawString(d,shell,g,sw/2-194,sh-DOCK_H+62,"LAUNCHER  TERMINAL  FILES  SETTINGS",36);XSetForeground(d,g,col(dark?"#8bf7ff":"#3657a6"));XFillRectangle(d,shell,g,sw/2-30,sh-15,60,3);XFreeGC(d,g);}
static void draw_frame(Client *c){GC g=XCreateGC(d,c->frame,0,0);XSetForeground(d,g,col(dark?"#11182c":"#d5ddf0"));XFillRectangle(d,c->frame,g,0,0,c->w,c->h);XSetForeground(d,g,col(dark?"#8bf7ff":"#3657a6"));XDrawRectangle(d,c->frame,g,0,0,c->w-1,c->h-1);XSetForeground(d,g,col(dark?"#1b2744":"#c2cce3"));XFillRectangle(d,c->frame,g,1,1,c->w-2,TITLE-1);XSetForeground(d,g,col(dark?"#e5f9ff":"#19243d"));XDrawString(d,c->frame,g,12,20,"NGOS application",15);XSetForeground(d,g,col("#ff5f57"));XFillArc(d,c->frame,g,c->w-76,8,14,14,0,360*64);XSetForeground(d,g,col("#ffc857"));XFillArc(d,c->frame,g,c->w-54,8,14,14,0,360*64);XSetForeground(d,g,col("#4de3a8"));XFillArc(d,c->frame,g,c->w-32,8,14,14,0,360*64);XFreeGC(d,g);}
static void focus_client(Client *c){if(!c)return;focus=c->client;XRaiseWindow(d,c->frame);XSetInputFocus(d,c->client,RevertToPointerRoot,CurrentTime);}
static void map_client(Window w){XWindowAttributes a;if(!XGetWindowAttributes(d,w,&a)||a.override_redirect)return;if(nclients>=MAX_CLIENTS)return;Client *c=&clients[nclients++];c->client=w;c->x=120+(nclients%3)*35;c->y=90+(nclients%3)*35;c->w=720;c->h=470;c->maximized=0;c->minimized=0;c->frame=XCreateSimpleWindow(d,root,c->x,c->y,c->w,c->h,0,col("#8bf7ff"),col("#11182c"));XSelectInput(d,c->frame,ExposureMask|ButtonPressMask|ButtonReleaseMask|PointerMotionMask);XAddToSaveSet(d,w);XReparentWindow(d,w,c->frame,2,TITLE);XResizeWindow(d,w,c->w-4,c->h-TITLE-2);XMapRaised(d,c->frame);XMapWindow(d,w);draw_frame(c);focus_client(c);}
static void close_client(Client *c){if(!c)return;XKillClient(d,c->client);}
static void toggle_max(Client *c){if(!c)return;if(!c->maximized){c->x=0;c->y=BAR;c->w=sw;c->h=sh-BAR-DOCK_H;c->maximized=1;}else{c->x=120;c->y=90;c->w=720;c->h=470;c->maximized=0;}XMoveResizeWindow(d,c->frame,c->x,c->y,c->w,c->h);XMoveResizeWindow(d,c->client,2,TITLE,c->w-4,c->h-TITLE-2);draw_frame(c);focus_client(c);}
static void key(XKeyEvent *e){KeySym k=XLookupKeysym(e,0);unsigned m=e->state&Mod4Mask;if(m&&k==XK_Return)launch("xterm");else if(m&&k==XK_d){dark=!dark;redraw();for(int i=0;i<nclients;i++)draw_frame(&clients[i]);}else if(m&&k==XK_m&&focus){Client *c=find_client(focus);if(c){c->minimized=1;XUnmapWindow(d,c->frame);}}else if(m&&(k>=XK_1&&k<=XK_4)){desk=k-XK_1;redraw();}else if(m&&k==XK_space)launch("xterm -e sh -c 'printf \"NGOS LAUNCHER\\n\\n1 Terminal\\n2 Files\\n3 Settings\\n\"; read'");else if(m&&k==XK_q)close_client(find_client(focus));}
static void button(XButtonEvent *e){Client *c=find_client(e->window);if(!c)return;focus_client(c);if(e->y<TITLE){if(e->x>c->w-90){close_client(c);return;}if(e->x>c->w-65){XUnmapWindow(d,c->frame);c->minimized=1;return;}if(e->x>c->w-45){toggle_max(c);return;}drag_client=c;drag_mode=1;drag_x=e->x_root;drag_y=e->y_root;drag_w=c->x;drag_h=c->y;}else if(e->x>c->w-18&&e->y>c->h-18){drag_client=c;drag_mode=2;drag_x=e->x_root;drag_y=e->y_root;drag_w=c->w;drag_h=c->h;}}
static void motion(XMotionEvent *e){if(drag_mode&&drag_client){Client *c=drag_client;if(drag_mode==1){c->x=drag_w+e->x_root-drag_x;c->y=drag_h+e->y_root-drag_y;XMoveWindow(d,c->frame,c->x,c->y);}else{c->w=(drag_w+e->x_root-drag_x>320)?drag_w+e->x_root-drag_x:320;c->h=(drag_h+e->y_root-drag_y>180)?drag_h+e->y_root-drag_y:180;XResizeWindow(d,c->frame,c->w,c->h);XResizeWindow(d,c->client,c->w-4,c->h-TITLE-2);draw_frame(c);}}}
int main(void){d=XOpenDisplay(0);if(!d)return 1;int s=DefaultScreen(d);root=RootWindow(d,s);sw=DisplayWidth(d,s);sh=DisplayHeight(d,s);XSelectInput(d,root,KeyPressMask);KeySym keys[]={XK_Return,XK_d,XK_m,XK_space,XK_q};for(unsigned i=0;i<5;i++)XGrabKey(d,XKeysymToKeycode(d,keys[i]),Mod4Mask,root,1,GrabModeAsync,GrabModeAsync);for(int i=0;i<4;i++)XGrabKey(d,XKeysymToKeycode(d,XK_1+i),Mod4Mask,root,1,GrabModeAsync,GrabModeAsync);XSetWindowAttributes wa={0};wa.override_redirect=True;wa.background_pixel=col("#060914");shell=XCreateWindow(d,root,0,0,sw,sh,0,CopyFromParent,InputOutput,CopyFromParent,CWOverrideRedirect|CWBackPixel,&wa);XSelectInput(d,shell,ExposureMask|KeyPressMask|PointerMotionMask);XMapWindow(d,shell);XLowerWindow(d,shell);redraw();for(;;){XEvent e;XNextEvent(d,&e);if(e.type==Expose)redraw();else if(e.type==KeyPress)key(&e.xkey);else if(e.type==MotionNotify){int left=sw/2-180;int n=(e.xmotion.x-left+36)/72;int nh=(n>=0&&n<ICONS)?n:-1;if(nh!=hover){hover=nh;redraw();}}}}
